### ISSUE TITLE
Other Models

### ISSUE THREAD

**Issue by pokeball99** [Engineer-of-Stuff/stable-diffusion-paperspace#24]
https://btdig.com/search?order=2&q=ckpt i'll leave it to your discretion which ones to include

~~also you've still yet to accept the friend request so that i can invite you to Auto's server lmao~~

**Comment by Cyberes** [comment]
The other models are at https://cyberes.github.io/stable-diffusion-models/
I don't want to add any more models since this notebook is getting really big. It's trivial to copy the code and download your own torrent link.
And yeah thanks for the invite, I bridge discord to matrix so I forgot to check.
