### ISSUE TITLE
2 stable diffusion webui folders?? 

### ISSUE THREAD

**Issue by Maki9009** [Engineer-of-Stuff/stable-diffusion-paperspace#67]
im confused so... why does it make a stable diffusion webui folder... and then it also creates another one inside the storage folder... do i have doubles of everything now? im i using extra storage for no reason?

**Comment by Cyberes** [comment]
I updated where the notebook installs the WebUI. You can change the path in settings to `repo_storage_dir = '/notebooks'` to use your old install. Delete the one you aren't using. (`/storage/` since it's mounted and  `/notebooks/` is copied to the machine. Big files in `/notebooks/` increases the start time of the machine.)
